### ISSUE TITLE
Most tests fail if the CLOSURE_HOISTING_OPT ("-optCH") is disabled in testRunner.py

### ISSUE THREAD

**Issue by FluXy** [GaijinEntertainment/quirrel#89]
The CLOSURE_HOISTING_OPT is off by default in quirrel. Is it required now?
Compiled with Visual Studio 2019.

Thank You!

**Comment by VasiliyRyabtsev** [comment]
Sounds like a bug, I will check in a few days. Thank you for reporting!

**Comment by VasiliyRyabtsev** [comment]
So, the optimization raises the function up the scope where possible. This can be done while it doesn't depend on the variables in the current scope. This changes AST and tests that compare resulting AST with the expected one fail.
I will think what to do with this.

(For the explanation: this optimization allows to reuse the single closure without recreating it from its function prototype where unnecessary. While it doesn't make much change on its own, it allows another optimizations to be built on top of this. For example, in daRg, a UI framework used in Dagor Engine, UI components are defined by functions and with this optimization we can avoid rebuilding/recreating a subtree of a UI scene if the function is unchanged, i.e. still references the same object.)

**Comment by VasiliyRyabtsev** [comment]
I think we will assume for now that tests expect the optimization to be enabled

**Comment by FluXy** [comment]
Maybe add a comment in the testRunner.py
