### ISSUE TITLE
string_view is not enabled under visual studio (__cplusplus is always 199711L)

### ISSUE THREAD

**Issue by FluXy** [GaijinEntertainment/quirrel#91]
#if __cplusplus >= 201703L
  using string_view = std::basic_string_view<SQChar>;
#else
  using string_view = string;
#endif

"The /Zc:__cplusplus compiler option enables the __cplusplus preprocessor macro to report an updated value for recent C++ language standards support. By default, Visual Studio always returns the value 199711L for the __cplusplus preprocessor macro."
https://learn.microsoft.com/en-us/cpp/build/reference/zc-cplusplus

Seems to be the same for sqrat

---

Even if the __cplusplus is correct the default C++ language standard for VS 2019 is C++14. 
cmake has set(CMAKE_CXX_STANDARD 11) but it should probably be 17 now (for string_view)?

**Comment by VasiliyRyabtsev** [comment]
I've updated the code
Will update Sqrat a bit later
