### ISSUE TITLE
Get script function from native not working anymore with sq_compile()

### ISSUE THREAD

**Issue by FluXy** [GaijinEntertainment/quirrel#92]
With the removal of this part:
https://github.com/GaijinEntertainment/quirrel/commit/fd462337c5c947c479e3d62fd3f8ee648c7db4fd#diff-3ce5ab9909a4ebc05d8c2da9a58ebc7f92713705f952b89b80e8619e9ae8900dL387-L398

the ability to get script functions with sqrat broke for me (Using the latest sqrat with m_rootTable->GetFunction()).
The root table keys before the commit included the "function" lines from scripts, afterwards it seems to be only native. Is there another way to get the functions (for Sqrat::Function)? Couldn't find it in the documentation.

Thanks!

**Comment by VasiliyRyabtsev** [comment]
This is where Quirrel and original Squirrel design diverge. Quirrel aims to be safe and strict. One of the aspect of this is that global storage with unrestricted access such as root table is fragile and should not be used. In Quirrel everything is local by default. For example in Enlisted and Cuisine Royale games not only root tables are empty, but even `::` operator is disabled.

The linked change is one of the steps that makes functions and classes local by default (this changes break compatibility).

If there is a native code that for compatibility reasons wants to read something from root table, script code such as
```
function foo() {}
```
can be rewritten as
```
::foo <- function foo() {}
```
Probably `#allow-root-table`  (or `#default:allow-root-table`) directive may be also needed in script to allow access to the root table.

**Comment by FluXy** [comment]
Thank you for the help! For Gaia Beyond we still need the global function support as the functions are also referenced in savegames. Changing the scripts to be more object based is too late for us (interface was designed in 2012). 

Managed to create a function now that replicates the "::foo <- " part as the default 😃 :

```
ExprStatement* SQParser::parseGlobalFunctionDeclStmt()
{
	SQInteger l = line(), c = column();

	assert(_token == TK_FUNCTION);
	Lex();

	Id* varname = (Id*)Expect(TK_IDENTIFIER);
	Expr* receiver = setCoordinates(newNode<RootExpr>(), l, c);
	assert(varname);
	Expr* expr = newNode<GetFieldExpr>(receiver, varname->id(), false, false); //-V522
	expr->setLineStartPos(receiver->lineStart()); expr->setColumnStartPos(receiver->columnStart());
	expr->setLineEndPos(l); expr->setColumnEndPos(c);
	Expect(_SC('('));
	FunctionDecl* f = CreateFunction(varname, false);
	f->setLineStartPos(l); f->setColumnStartPos(c);

	DeclExpr* d = newNode<DeclExpr>(f); //-V522
	setCoordinates(d, l, c);
	expr = newNode<BinExpr>(TO_NEWSLOT, expr, static_cast<Expr*>(d));
	return copyCoordinates(expr, newNode<ExprStatement>(expr));
}

```

and in SQParser::Factor():

```
    case TK_IDENTIFIER: {
            Id* id = newId(_lex._svalue);
            id->setLineStartPos(l); id->setColumnStartPos(c);
            Lex();
            if(_token == _SC('('))
            {
                r = setCoordinates(newNode<RootExpr>(), l, c);

                r = newNode<GetFieldExpr>(r, id->id(), false, false); //-V522
			    r->setLineStartPos(r->lineStart()); r->setColumnStartPos(r->columnStart());
			    r->setLineEndPos(l); r->setColumnEndPos(c);
            }
            else
            {
                r = id;
            }
        }
        break;
```

If there is a simpler way let me know

**Comment by VasiliyRyabtsev** [comment]
Your change seems to make it impossible to call local functions - all the identifiers following with brackets will be unconditionally transformed into root table lookups.
Also yes, the simpler solution may look like this:

```
diff --git a/squirrel/sqastcodegen.cpp b/squirrel/sqastcodegen.cpp
index 1c824f2..a9f0f1a 100644
--- a/squirrel/sqastcodegen.cpp
+++ b/squirrel/sqastcodegen.cpp
@@ -791,6 +791,11 @@ void CodegenVisitor::visitParamDecl(ParamDecl *param) {
 void CodegenVisitor::visitFunctionDecl(FunctionDecl *funcDecl) {
     addLineNumber(funcDecl);
 
+    //_fs->PushTarget(0); // This will put the function to the named field of `this`
+    _fs->AddInstruction(_OP_LOADROOT, _fs->PushTarget()); // This will put the function to the named field of root table
+
+    _fs->AddInstruction(_OP_LOAD, _fs->PushTarget(), _fs->GetConstant(_fs->CreateString(funcDecl->name())));
+
     SQFuncState *savedChildFsAtRoot = _childFs; // may be non-null when processing default argument that is declared as function/lambda
     _childFs = _fs->PushChildState(_ss(_vm));
 
@@ -848,6 +853,8 @@ void CodegenVisitor::visitFunctionDecl(FunctionDecl *funcDecl) {
     _childFs = savedChildFsAtRoot;
 
     _fs->AddInstruction(_OP_CLOSURE, _fs->PushTarget(), _fs->_functions.size() - 1, funcDecl->isLambda() ? 1 : 0);
+    EmitDerefOp(_OP_NEWSLOT);
+    _fs->PopTarget();
 }
 
 SQTable* CodegenVisitor::GetScopedConstsTable()
diff --git a/squirrel/sqastparser.cpp b/squirrel/sqastparser.cpp
index 4ce6cd5..118d8e8 100644
--- a/squirrel/sqastparser.cpp
+++ b/squirrel/sqastparser.cpp
@@ -337,7 +337,8 @@ Statement* SQParser::parseStatement(bool closeframe)
         Lex();
         return result;
     case TK_FUNCTION:
-        result = parseLocalFunctionDeclStmt(false);
+        result = parseFunctionStatement();
         break;
     case TK_CLASS:
         result = parseLocalClassDeclStmt(false);
@@ -1835,6 +1836,18 @@ FunctionDecl* SQParser::CreateFunction(Id *name, bool lambda, bool ctor)
     return f;
 }
 
+
+FunctionDecl* SQParser::parseFunctionStatement()
+{
+    SQInteger l = _lex._currentline, c = _lex._currentcolumn;
+    Consume(TK_FUNCTION);
+    Id *funcName = (Id *)Expect(TK_IDENTIFIER);
+    Expect(_SC('('));
+    FunctionDecl *d = CreateFunction(funcName);
+    setCoordinates(d, l, c);
+    return d;
+}
+
 } // namespace SQCompilation
 
```

The commented line `//_fs->PushTarget(0);` will return original Squirrel behavior, where declared functions were put into `this`. It might be a root table, but in case of modules it is a module own table originally used to prevent accidentally polluting root table.
`_fs->AddInstruction(_OP_LOADROOT, _fs->PushTarget());` will explicitly put the function to the root table.

**Comment by VasiliyRyabtsev** [comment]
I understand that there may be many reasons to use root table, but I highly dislike the original Squirrel behavior. Wouldn't regexp-based search & replace of `function foo(args)` into `::foo <- function foo_impl(args)` do in your case? This was successfully done with literally megabytes of script code in WarThunder. I am a huge proponent of explicit code and dislike the original Squirrel approach where an reference to a variable might generate two different versions of code depending whether and identifier can be found as a local variable. Otherwise, when it is not a local variable, the compiler generated code for looking up identifier in `this` and , if not found there, in the root table. This made script code error-prone and difficult to check/verify/understand both by human and compiler/analyzer.

**Comment by VasiliyRyabtsev** [comment]
Oh, and the second part of your change - allowing to find named slots in a root table, but only when no such variable or constant exists, may be done like this

```
diff --git a/squirrel/sqastcodegen.cpp b/squirrel/sqastcodegen.cpp
index 1c824f2..3b4d0c4 100644
--- a/squirrel/sqastcodegen.cpp
+++ b/squirrel/sqastcodegen.cpp
@@ -1652,11 +1659,8 @@ void CodegenVisitor::visitId(Id *id) {
         * the _OP_GET instruction.
 
         */
-        // TODO: probably we need a special handling for some corner cases
-        if (!(_fs->lang_features & LF_TOOLS_COMPILE_CHECK))
-            reportDiagnostic(id, DiagnosticsId::DI_UNKNOWN_SYMBOL, id->id());
-
-        _fs->PushTarget(0);
+        //_fs->PushTarget(0);
+        _fs->AddInstruction(_OP_LOADROOT, _fs->PushTarget());
         _fs->AddInstruction(_OP_LOAD, _fs->PushTarget(), _fs->GetConstant(idObj));
         if (!_donot_get) {
             Emit2ArgsOP(_OP_GET);

```

**Comment by VasiliyRyabtsev** [comment]
I think between two options - using identifiers not found in the local scope as fields in either `this` or root table - I'd choose using `this` (`_fs->PushTarget(0)`) and not root table (`_fs->AddInstruction(_OP_LOADROOT, _fs->PushTarget())`). This is consistent with the original Squirrel behavior, we possibly don't want more incompatible dialects.
And for making modules to use the root table instead of custom table for its `this`, the change is simple:
```
--- a/prog/1stPartyLibs/quirrel/quirrel/sqmodules/sqmodules.cpp
+++ b/prog/1stPartyLibs/quirrel/quirrel/sqmodules/sqmodules.cpp
@@ -394,7 +394,7 @@ bool SqModules::requireModule(const char *requested_fn, bool must_exist, const c
   runningScripts.emplace_back(resolvedFn.c_str());
 
   sq_pushobject(vm, scriptClosure.GetObject());
-  sq_newtable(vm);
+  sq_pushroottable(vm);
 
   SQRAT_ASSERT(sq_gettype(vm, -1) == OT_TABLE);
   Sqrat::Object objThis = Sqrat::Var<Sqrat::Object>(vm, -1).value;
```

**Comment by FluXy** [comment]
Thanks for the help! I tried it out (the non-modules) but it didn't work with native functions like dofile.

> Wouldn't regexp-based search & replace of function foo(args) into ::foo <- function foo_impl(args) do in your case?
For us the scripts are mainly for the story and are created by non-programmers - the less verbose the better.
